// @ts-nocheck
// AUTO-GENERATED by scripts/generate-mcp.ts — do not edit manually
import { z } from "zod";
import type { RegisterTools } from "../types";
import {
  READ_ONLY_ANNOTATIONS,
  WRITE_ANNOTATIONS,
  DESTRUCTIVE_ANNOTATIONS,
  toMcpResult,
  withErrorHandling,
} from "../types";
import {
  getPriceListsList,
  getPriceLists,
  getPriceList,
  getPriceListLockState,
  createPriceList,
  updatePriceList,
  deletePriceList,
  getPriceListItems,
  getPriceListItem,
  createPriceListItem,
  updatePriceListItem,
  deletePriceListItem,
  getPriceListItemBreaks,
  upsertPriceListItemBreaks,
  getPriceListRules,
  getPriceListRule,
  createPriceListRule,
  updatePriceListRule,
  deletePriceListRule,
  getPriceListAssignments,
  createPriceListAssignment,
  deletePriceListAssignment,
  syncPriceListAssignments,
  createPriceListVersion,
  archiveSiblingVersions,
  duplicatePriceList,
  getPriceListVersions,
  getActivePriceListsForCustomer,
  getPriceListItemsForResolution,
  getApplicableRules,
  getSalesOrdersByPriceList,
  getCustomersByDefaultPriceList,
  getPriceListsForItem,
  resolvePrice,
  resolvePrices,
  getOverlappingPriceLists,
  getOverlapIdsForPriceLists,
} from "~/modules/pricing/pricing.service";
import {
  priceListValidator,
  priceListItemValidator,
  priceListRuleValidator,
  priceListAssignmentValidator,
} from "~/modules/pricing/pricing.models";

export const registerPricingTools: RegisterTools = (server, ctx) => {
  server.registerTool(
    "pricing_getPriceListsList",
    {
      description: "get price lists list",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListsList(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListsList"),
  );

  server.registerTool(
    "pricing_getPriceLists",
    {
      description: "get price lists",
      inputSchema: {
      args: z.object({
    limit: z.number().int().default(100),
    offset: z.number().int().default(0),
    search: z.string().optional(),
    customerId: z.string().optional()
  }).optional(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceLists(ctx.client, ctx.companyId, params.args);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceLists"),
  );

  server.registerTool(
    "pricing_getPriceList",
    {
      description: "get price list",
      inputSchema: {
      id: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceList(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceList"),
  );

  server.registerTool(
    "pricing_getPriceListLockState",
    {
      description: "get price list lock state",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListLockState(ctx.client, params.priceListId);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListLockState"),
  );

  server.registerTool(
    "pricing_createPriceList",
    {
      description: "create price list",
      inputSchema: {
      data: priceListValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createPriceList(ctx.client, ctx.companyId, ctx.userId, params.data);
      return toMcpResult(result);
    }, "Failed: pricing_createPriceList"),
  );

  server.registerTool(
    "pricing_updatePriceList",
    {
      description: "update price list",
      inputSchema: {
      id: z.string(),
      data: priceListValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePriceList(ctx.client, params.id, ctx.userId, params.data);
      return toMcpResult(result);
    }, "Failed: pricing_updatePriceList"),
  );

  server.registerTool(
    "pricing_deletePriceList",
    {
      description: "delete price list",
      inputSchema: {
      id: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePriceList(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: pricing_deletePriceList"),
  );

  server.registerTool(
    "pricing_getPriceListItems",
    {
      description: "get price list items",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListItems(ctx.client, params.priceListId);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListItems"),
  );

  server.registerTool(
    "pricing_getPriceListItem",
    {
      description: "get price list item",
      inputSchema: {
      id: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListItem(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListItem"),
  );

  server.registerTool(
    "pricing_createPriceListItem",
    {
      description: "create price list item",
      inputSchema: {
      data: priceListItemValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createPriceListItem(ctx.client, ctx.companyId, ctx.userId, params.data);
      return toMcpResult(result);
    }, "Failed: pricing_createPriceListItem"),
  );

  server.registerTool(
    "pricing_updatePriceListItem",
    {
      description: "update price list item",
      inputSchema: {
      id: z.string(),
      data: priceListItemValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePriceListItem(ctx.client, params.id, ctx.userId, params.data);
      return toMcpResult(result);
    }, "Failed: pricing_updatePriceListItem"),
  );

  server.registerTool(
    "pricing_deletePriceListItem",
    {
      description: "delete price list item",
      inputSchema: {
      id: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePriceListItem(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: pricing_deletePriceListItem"),
  );

  server.registerTool(
    "pricing_getPriceListItemBreaks",
    {
      description: "get price list item breaks",
      inputSchema: {
      priceListItemId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListItemBreaks(ctx.client, params.priceListItemId);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListItemBreaks"),
  );

  server.registerTool(
    "pricing_upsertPriceListItemBreaks",
    {
      description: "upsert price list item breaks",
      inputSchema: {
      db: z.any(),
      priceListItemId: z.string(),
      breaks: z.any(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await upsertPriceListItemBreaks(ctx.client, params.db, params.priceListItemId, ctx.companyId, ctx.userId, params.breaks);
      return toMcpResult(result);
    }, "Failed: pricing_upsertPriceListItemBreaks"),
  );

  server.registerTool(
    "pricing_getPriceListRules",
    {
      description: "get price list rules",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListRules(ctx.client, params.priceListId);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListRules"),
  );

  server.registerTool(
    "pricing_getPriceListRule",
    {
      description: "get price list rule",
      inputSchema: {
      id: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListRule(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListRule"),
  );

  server.registerTool(
    "pricing_createPriceListRule",
    {
      description: "create price list rule",
      inputSchema: {
      data: priceListRuleValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createPriceListRule(ctx.client, ctx.companyId, ctx.userId, params.data);
      return toMcpResult(result);
    }, "Failed: pricing_createPriceListRule"),
  );

  server.registerTool(
    "pricing_updatePriceListRule",
    {
      description: "update price list rule",
      inputSchema: {
      id: z.string(),
      data: priceListRuleValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await updatePriceListRule(ctx.client, params.id, ctx.userId, params.data);
      return toMcpResult(result);
    }, "Failed: pricing_updatePriceListRule"),
  );

  server.registerTool(
    "pricing_deletePriceListRule",
    {
      description: "delete price list rule",
      inputSchema: {
      id: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePriceListRule(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: pricing_deletePriceListRule"),
  );

  server.registerTool(
    "pricing_getPriceListAssignments",
    {
      description: "get price list assignments",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListAssignments(ctx.client, params.priceListId);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListAssignments"),
  );

  server.registerTool(
    "pricing_createPriceListAssignment",
    {
      description: "create price list assignment",
      inputSchema: {
      data: priceListAssignmentValidator,
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createPriceListAssignment(ctx.client, ctx.companyId, ctx.userId, params.data);
      return toMcpResult(result);
    }, "Failed: pricing_createPriceListAssignment"),
  );

  server.registerTool(
    "pricing_deletePriceListAssignment",
    {
      description: "delete price list assignment",
      inputSchema: {
      id: z.string(),
    },
      annotations: DESTRUCTIVE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await deletePriceListAssignment(ctx.client, params.id);
      return toMcpResult(result);
    }, "Failed: pricing_deletePriceListAssignment"),
  );

  server.registerTool(
    "pricing_syncPriceListAssignments",
    {
      description: "sync price list assignments",
      inputSchema: {
      db: z.any(),
      priceListId: z.string(),
      assignments: z.object({
    customerIds: z.array(z.string()).optional(),
    customerTypeIds: z.array(z.string()).optional()
  }),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await syncPriceListAssignments(ctx.client, params.db, params.priceListId, ctx.companyId, ctx.userId, params.assignments);
      return toMcpResult(result);
    }, "Failed: pricing_syncPriceListAssignments"),
  );

  server.registerTool(
    "pricing_createPriceListVersion",
    {
      description: "create price list version",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await createPriceListVersion(ctx.client, params.priceListId, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: pricing_createPriceListVersion"),
  );

  server.registerTool(
    "pricing_archiveSiblingVersions",
    {
      description: "archive sibling versions",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await archiveSiblingVersions(ctx.client, params.priceListId, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: pricing_archiveSiblingVersions"),
  );

  server.registerTool(
    "pricing_duplicatePriceList",
    {
      description: "duplicate price list",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await duplicatePriceList(ctx.client, params.priceListId, ctx.companyId, ctx.userId);
      return toMcpResult(result);
    }, "Failed: pricing_duplicatePriceList"),
  );

  server.registerTool(
    "pricing_getPriceListVersions",
    {
      description: "get price list versions",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListVersions(ctx.client, params.priceListId);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListVersions"),
  );

  server.registerTool(
    "pricing_getActivePriceListsForCustomer",
    {
      description: "get active price lists for customer",
      inputSchema: {
      customerId: z.string(),
      customerTypeId: z.string().nullable(),
      date: z.string(),
      currencyCode: z.string().optional(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getActivePriceListsForCustomer(ctx.client, ctx.companyId, params.customerId, params.customerTypeId, params.date, params.currencyCode);
      return toMcpResult(result);
    }, "Failed: pricing_getActivePriceListsForCustomer"),
  );

  server.registerTool(
    "pricing_getPriceListItemsForResolution",
    {
      description: "get price list items for resolution",
      inputSchema: {
      priceListId: z.string(),
      itemId: z.string(),
      itemPostingGroupId: z.string().nullable(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListItemsForResolution(ctx.client, params.priceListId, params.itemId, params.itemPostingGroupId);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListItemsForResolution"),
  );

  server.registerTool(
    "pricing_getApplicableRules",
    {
      description: "get applicable rules",
      inputSchema: {
      priceListId: z.string(),
      quantity: z.number(),
      customerTypeId: z.string().nullable(),
      itemId: z.string(),
      itemPostingGroupId: z.string().nullable(),
      date: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getApplicableRules(ctx.client, params.priceListId, params.quantity, params.customerTypeId, params.itemId, params.itemPostingGroupId, params.date);
      return toMcpResult(result);
    }, "Failed: pricing_getApplicableRules"),
  );

  server.registerTool(
    "pricing_getSalesOrdersByPriceList",
    {
      description: "get sales orders by price list",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getSalesOrdersByPriceList(ctx.client, params.priceListId);
      return toMcpResult(result);
    }, "Failed: pricing_getSalesOrdersByPriceList"),
  );

  server.registerTool(
    "pricing_getCustomersByDefaultPriceList",
    {
      description: "get customers by default price list",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getCustomersByDefaultPriceList(ctx.client, params.priceListId);
      return toMcpResult(result);
    }, "Failed: pricing_getCustomersByDefaultPriceList"),
  );

  server.registerTool(
    "pricing_getPriceListsForItem",
    {
      description: "get price lists for item",
      inputSchema: {
      itemId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getPriceListsForItem(ctx.client, params.itemId);
      return toMcpResult(result);
    }, "Failed: pricing_getPriceListsForItem"),
  );

  server.registerTool(
    "pricing_resolvePrice",
    {
      description: "resolve price",
      inputSchema: {
      input: z.any(),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await resolvePrice(ctx.client, ctx.companyId, params.input);
      return toMcpResult(result);
    }, "Failed: pricing_resolvePrice"),
  );

  server.registerTool(
    "pricing_resolvePrices",
    {
      description: "resolve prices",
      inputSchema: {
      inputs: z.array(z.any()),
    },
      annotations: WRITE_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await resolvePrices(ctx.client, ctx.companyId, params.inputs);
      return toMcpResult(result);
    }, "Failed: pricing_resolvePrices"),
  );

  server.registerTool(
    "pricing_getOverlappingPriceLists",
    {
      description: "get overlapping price lists",
      inputSchema: {
      priceListId: z.string(),
    },
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOverlappingPriceLists(ctx.client, ctx.companyId, params.priceListId);
      return toMcpResult(result);
    }, "Failed: pricing_getOverlappingPriceLists"),
  );

  server.registerTool(
    "pricing_getOverlapIdsForPriceLists",
    {
      description: "get overlap ids for price lists",
      inputSchema: {},
      annotations: READ_ONLY_ANNOTATIONS,
    },
    withErrorHandling(async (params) => {
      const result = await getOverlapIdsForPriceLists(ctx.client, ctx.companyId);
      return toMcpResult(result);
    }, "Failed: pricing_getOverlapIdsForPriceLists"),
  );
};
