import { Font } from "@react-pdf/renderer";
import { BUNDLED_FONTS } from "./fonts.data";

/**
 * Document fonts for PDFs. Every Google font offered in the template editor is
 * bundled into the package as base64 woff (`fonts.data.ts`, generated by
 * `pnpm --filter @carbon/documents generate:fonts`) and registered in-process — there
 * is NO network at render time. (The previous approach fetched Google's CSS at
 * render, which failed intermittently on Vercel and crashed with
 * "Font family not registered: <font>".)
 *
 * Format is woff, not woff2: react-pdf only supports TTF/WOFF, and this fontkit's
 * woff2/brotli decoder corrupts shared state when many woff2 fonts are decoded in
 * one process (react-pdf preloads every registered font) → DataView range errors
 * at embed. woff (zlib) is stateless and decodes all families reliably.
 *
 * Helvetica / Times-Roman / Courier are PDF standard fonts and need no registration.
 */

/** PDF standard fonts — usable without registration. */
export const BUILT_IN_FONTS = ["Helvetica", "Times-Roman", "Courier"];

/**
 * Inter fallback via remote TTF URLs, used ONLY when Inter is not present in the
 * bundled data — i.e. before the generator has been run. Once bundled, Inter is
 * registered from local woff with no network. Kept so the default body font
 * still renders on a fresh checkout.
 */
const INTER_URL_FALLBACK = {
  family: "Inter",
  fonts: [
    {
      src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuLyfMZhrib2Bg-4.ttf"
    },
    {
      src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuOKfMZhrib2Bg-4.ttf",
      fontWeight: 300
    },
    {
      src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuI6fMZhrib2Bg-4.ttf",
      fontWeight: 500
    },
    {
      src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuFuYMZhrib2Bg-4.ttf",
      fontWeight: 700
    },
    {
      src: "https://fonts.gstatic.com/s/inter/v13/UcCO3FwrK3iLTeHuS_fvQtMwCp50KnMw2boKoduKmMEVuBWYMZhrib2Bg-4.ttf",
      fontWeight: 900
    }
  ]
};

let registered = false;

/**
 * Register every bundled document font with react-pdf. Idempotent and
 * synchronous: bundled fonts are base64 woff decoded in-process, so this never
 * hits the network and never fails. Safe to call on every render.
 */
export function registerDocumentFonts(): void {
  if (registered) return;
  registered = true;

  for (const { family, fonts } of BUNDLED_FONTS) {
    Font.register({ family, fonts });
  }

  // Pre-generation safety net: keep the default (Inter) working until the
  // bundled data has been generated.
  if (!BUNDLED_FONTS.some((f) => f.family === "Inter")) {
    Font.register(INTER_URL_FALLBACK);
  }
}

/**
 * Back-compat entry point. Routes call `await ensureFont(settings.fontFamily)`
 * before render; registration is now up-front and local, so the `family` arg is
 * ignored — everything is registered at once. Kept async so existing call sites
 * don't change.
 */
export async function ensureFont(_family?: string): Promise<void> {
  registerDocumentFonts();
}

/**
 * Resolve a requested font family to one that is safe to render: the family
 * itself when it is a PDF built-in or has been registered, otherwise "Helvetica".
 * Never returns an unregistered family, so react-pdf cannot throw
 * "Font family not registered".
 */
export function getSafeFontFamily(family: string | undefined | null): string {
  registerDocumentFonts();
  if (!family) return "Helvetica";
  if (BUILT_IN_FONTS.includes(family)) return family;
  return Font.getRegisteredFontFamilies().includes(family)
    ? family
    : "Helvetica";
}
