import { existsSync, unlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { APP_CHOICES } from "../constants.js";
import type { JwtCreds } from "./jwt.js";
import { type PortMap, SHARED_REDIS_PORT } from "./ports.js";

export function renderEnv(opts: {
  slug: string;
  ports: PortMap;
  redisDb: number;
  jwt: JwtCreds;
  /**
   * Worktree-aware hostname prefix matching what portless registers for
   * app dev-servers. `null` on the main checkout (portless skips prefixing
   * there), the sanitized last branch segment otherwise — e.g. for branch
   * `feat/boo` in a linked worktree, prefix is `boo` and hostnames look like
   * `boo.erp.dev`. Mirrors `branchToPrefix` in services/portless.ts.
   */
  branchPrefix: string | null;
}): string {
  const { slug, ports, redisDb, jwt, branchPrefix } = opts;
  const host = (sub: string) =>
    branchPrefix ? `${branchPrefix}.${sub}.dev` : `${sub}.dev`;

  const lines: string[] = [];
  lines.push("# Generated by crbn. Do not edit by hand.");
  lines.push("# Vite/React Router auto-load this file alongside .env;");
  lines.push("# values here override .env. The user's .env is left untouched.");
  lines.push("");
  lines.push(`CARBON_WORKTREE=${slug}`);
  lines.push("PORTLESS_TLD=dev");
  lines.push("");
  lines.push("# Internal compose ports (apps do not read these directly)");
  for (const [k, v] of Object.entries(ports)) lines.push(`${k}=${v}`);
  lines.push("");
  lines.push("# App-facing URLs (portless hostnames)");
  lines.push(`DOMAIN=${host("erp")}`);
  lines.push(`ERP_URL=https://${host("erp")}`);
  lines.push(`MES_URL=https://${host("mes")}`);
  lines.push(`VERCEL_URL=https://${host("erp")}`);
  lines.push(`GTM_URL=https://${host("starter")}`);
  lines.push("");
  lines.push(
    "# Supabase (per-worktree dev keys, minted from random JWT_SECRET)"
  );
  lines.push(`SUPABASE_URL=https://${host("api")}`);
  lines.push(
    `SUPABASE_DB_URL=postgresql://postgres:postgres@localhost:${ports.PORT_DB}/postgres`
  );
  lines.push("PGSSLMODE=disable");
  lines.push(`SUPABASE_JWT_SECRET=${jwt.secret}`);
  lines.push(`SUPABASE_ANON_KEY=${jwt.anonKey}`);
  lines.push(`SUPABASE_SERVICE_ROLE_KEY=${jwt.serviceKey}`);
  // Stable, branch-independent OAuth callback hostname (api.carbon.dev). Lets
  // a single redirect URI live in the Google/Azure OAuth client config across
  // all worktrees. crbn up registers `api.carbon` as a portless alias to the
  // current worktree's PORT_API, so whichever worktree is `up` services
  // OAuth callbacks.
  lines.push(
    `SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI=https://api.carbon.dev/auth/v1/callback`
  );
  lines.push(
    `SUPABASE_AUTH_EXTERNAL_AZURE_REDIRECT_URI=https://api.carbon.dev/auth/v1/callback`
  );
  lines.push("");
  lines.push("# Aux services");
  lines.push(`REDIS_URL=redis://localhost:${SHARED_REDIS_PORT}/${redisDb}`);
  lines.push("INNGEST_DEV=1");
  lines.push(`INNGEST_BASE_URL=http://localhost:${ports.PORT_INNGEST}`);
  lines.push("");
  return lines.join("\n");
}

export function writeEnv(worktreeRoot: string, content: string) {
  writeFileSync(join(worktreeRoot, ".env.local"), content);
}

/**
 * Write `apps/<id>/portless.json` so portless serves the app under the
 * worktree-prefixed hostname even from the main checkout.
 *
 * Portless's auto-prefixing only fires inside a linked git worktree (it
 * compares `--git-dir` against `--git-common-dir`). When a non-default branch
 * is checked out in the main checkout we still want `<prefix>.<app>.dev`, so
 * we stamp the full name explicitly. In linked worktrees we leave the file
 * absent — portless detects the prefix itself, and stamping a literal name
 * here would double-prefix (`<prefix>.<prefix>.<app>`).
 *
 * Removes any prior portless.json when the prefix is gone, so stale configs
 * from a previous `crbn up` on a feature branch don't leak into a default
 * branch run.
 */
export function syncAppPortlessConfigs(opts: {
  worktreeRoot: string;
  branchPrefix: string | null;
  linked: boolean;
}) {
  const { worktreeRoot, branchPrefix, linked } = opts;
  for (const { value: appId } of APP_CHOICES) {
    const path = join(worktreeRoot, "apps", appId, "portless.json");
    const shouldStamp = !linked && branchPrefix !== null;
    if (shouldStamp) {
      writeFileSync(
        path,
        `${JSON.stringify({ name: `${branchPrefix}.${appId}` }, null, 2)}\n`
      );
    } else if (existsSync(path)) {
      unlinkSync(path);
    }
  }
}
