import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { JwtCreds } from "./jwt.js";
import { type PortMap, SHARED_REDIS_PORT } from "./ports.js";

export function renderEnv(opts: {
  slug: string;
  ports: PortMap;
  redisDb: number;
  jwt: JwtCreds;
  /**
   * Slugified branch name. Becomes the second-level subdomain.
   * Hostname pattern: <app>.<branchSegment>.dev — e.g. erp.feat-x.dev
   */
  branchSegment: string;
}): string {
  const { slug, ports, redisDb, jwt, branchSegment } = opts;
  const host = (sub: string) => `${sub}.${branchSegment}.dev`;

  const lines: string[] = [];
  lines.push("# Generated by crbn. Do not edit by hand.");
  lines.push("# Vite/React Router auto-load this file alongside .env;");
  lines.push("# values here override .env. The user's .env is left untouched.");
  lines.push("");
  lines.push(`CARBON_WORKTREE=${slug}`);
  lines.push("PORTLESS_TLD=dev");
  lines.push("");
  lines.push("# Internal compose ports (apps do not read these directly)");
  for (const [k, v] of Object.entries(ports)) lines.push(`${k}=${v}`);
  lines.push("");
  lines.push("# App-facing URLs (portless hostnames)");
  lines.push(`DOMAIN=${host("erp")}`);
  lines.push(`ERP_URL=https://${host("erp")}`);
  lines.push(`MES_URL=https://${host("mes")}`);
  lines.push(`VERCEL_URL=https://${host("erp")}`);
  lines.push(`GTM_URL=https://${host("starter")}`);
  lines.push("");
  lines.push(
    "# Supabase (per-worktree dev keys, minted from random JWT_SECRET)"
  );
  lines.push(`SUPABASE_URL=https://${host("api")}`);
  lines.push(
    `SUPABASE_DB_URL=postgresql://postgres:postgres@localhost:${ports.PORT_DB}/postgres`
  );
  lines.push("PGSSLMODE=disable");
  lines.push(`SUPABASE_JWT_SECRET=${jwt.secret}`);
  lines.push(`SUPABASE_ANON_KEY=${jwt.anonKey}`);
  lines.push(`SUPABASE_SERVICE_ROLE_KEY=${jwt.serviceKey}`);
  // Stable, branch-independent OAuth callback hostname (api.carbon.dev). Lets
  // a single redirect URI live in the Google/Azure OAuth client config across
  // all worktrees. crbn up registers `api.carbon` as a portless alias to the
  // current worktree's PORT_API, so whichever worktree is `up` services
  // OAuth callbacks.
  lines.push(
    `SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI=https://api.carbon.dev/auth/v1/callback`
  );
  lines.push(
    `SUPABASE_AUTH_EXTERNAL_AZURE_REDIRECT_URI=https://api.carbon.dev/auth/v1/callback`
  );
  lines.push("");
  lines.push("# Aux services");
  lines.push(`REDIS_URL=redis://localhost:${SHARED_REDIS_PORT}/${redisDb}`);
  lines.push("INNGEST_DEV=1");
  lines.push(`INNGEST_BASE_URL=http://localhost:${ports.PORT_INNGEST}`);
  lines.push("");
  return lines.join("\n");
}

export function writeEnv(worktreeRoot: string, content: string) {
  writeFileSync(join(worktreeRoot, ".env.local"), content);
}
