import { writeFileSync } from "node:fs";
import { join } from "node:path";
import type { PortMap } from "./ports.js";

// Well-known supabase CLI dev keys (signed with the dev JWT secret).
// Same values supabase start uses today, so existing app code keeps working.
const DEV_JWT_SECRET = "super-secret-jwt-token-with-at-least-32-characters-long";
const DEV_ANON_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0";
const DEV_SERVICE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU";

export function renderEnv(opts: { slug: string; ports: PortMap }): string {
  const { slug, ports } = opts;
  const lines: string[] = [];
  lines.push("# Generated by scripts/dev/cli.ts. Do not edit by hand.");
  lines.push("# Vite/React Router auto-load this file alongside .env;");
  lines.push("# values here override .env. The user's .env is left untouched.");
  lines.push("");
  lines.push(`CARBON_WORKTREE=${slug}`);
  lines.push("PORTLESS_TLD=dev");
  lines.push("");
  lines.push("# Internal compose ports (apps do not read these directly)");
  for (const [k, v] of Object.entries(ports)) lines.push(`${k}=${v}`);
  lines.push("");
  lines.push("# App-facing URLs (per-worktree portless hostnames)");
  lines.push(`DOMAIN=${slug}.dev`);
  lines.push(`ERP_URL=https://erp.${slug}.dev`);
  lines.push(`MES_URL=https://mes.${slug}.dev`);
  lines.push(`VERCEL_URL=https://erp.${slug}.dev`);
  lines.push(`GTM_URL=https://starter.${slug}.dev`);
  lines.push("");
  lines.push("# Supabase (well-known dev keys)");
  lines.push(`SUPABASE_URL=https://api.${slug}.dev`);
  lines.push(
    `SUPABASE_DB_URL=postgresql://postgres:postgres@localhost:${ports.PORT_DB}/postgres`
  );
  lines.push("PGSSLMODE=disable");
  lines.push(`SUPABASE_JWT_SECRET=${DEV_JWT_SECRET}`);
  lines.push(`SUPABASE_ANON_KEY=${DEV_ANON_KEY}`);
  lines.push(`SUPABASE_SERVICE_ROLE_KEY=${DEV_SERVICE_KEY}`);
  lines.push(
    `SUPABASE_AUTH_EXTERNAL_GOOGLE_REDIRECT_URI=https://api.${slug}.dev/auth/v1/callback`
  );
  lines.push(
    `SUPABASE_AUTH_EXTERNAL_AZURE_REDIRECT_URI=https://api.${slug}.dev/auth/v1/callback`
  );
  lines.push("");
  lines.push("# Aux services");
  lines.push(`REDIS_URL=redis://localhost:${ports.PORT_REDIS}`);
  lines.push("INNGEST_DEV=1");
  lines.push(`INNGEST_BASE_URL=http://localhost:${ports.PORT_INNGEST}`);
  lines.push("");
  return lines.join("\n");
}

export function writeEnv(worktreeRoot: string, content: string) {
  writeFileSync(join(worktreeRoot, ".env.local"), content);
}
