// Generates src/pdf/fonts.data.ts: the document fonts offered in the template
// editor, embedded as base64 woff data URIs so react-pdf registers them
// in-process with NO network at render time (the old runtime fetch to Google
// Fonts was the source of "Font family not registered" crashes on Vercel).
//
// Bytes come from the @fontsource/* packages (OFL/Apache, redistributable).
//
// FORMAT = woff (NOT woff2): react-pdf preloads every registered font, and this
// fontkit's woff2/brotli decoder corrupts shared state when many woff2 fonts are
// decoded in one process → "Offset is outside the bounds of the DataView" at
// embed. woff (zlib/tiny-inflate) is stateless and decodes all families fine.
// (Verified: all 8 families render with woff; woff2 crashes once all are registered.)
//
// Runs automatically on the root `postinstall` (output is gitignored). Run
// manually to refresh:  pnpm --filter @carbon/documents generate:fonts
import { createRequire } from "node:module";
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, "..", "src", "pdf", "fonts.data.ts");

// The "latin" subset covers basic + Western European text and keeps the bundle
// small. Family list mirrors DOCUMENT_FONTS in template/schema.ts (Google fonts
// only — Helvetica/Times/Courier are PDF built-ins, Inter is the default body).
const SUBSET = "latin";
const FAMILIES = [
  { family: "Inter", pkg: "@fontsource/inter", weights: [300, 400, 500, 700, 900] },
  { family: "Roboto", pkg: "@fontsource/roboto", weights: [400, 700] },
  { family: "Open Sans", pkg: "@fontsource/open-sans", weights: [400, 700] },
  { family: "Lato", pkg: "@fontsource/lato", weights: [400, 700] },
  { family: "Montserrat", pkg: "@fontsource/montserrat", weights: [400, 700] },
  { family: "Merriweather", pkg: "@fontsource/merriweather", weights: [400, 700] },
  { family: "Playfair Display", pkg: "@fontsource/playfair-display", weights: [400, 700] },
  { family: "Lora", pkg: "@fontsource/lora", weights: [400, 700] },
];

function filesDir(pkg) {
  // Locate the package's files/ dir on disk. fs ignores the package's "exports"
  // map (which can block require.resolve of ./package.json or ./files/*), so we
  // probe the likely install locations directly, then fall back to require.
  const candidates = [
    join(here, "..", "node_modules", pkg, "files"), // pnpm: documents' own node_modules
    join(here, "..", "..", "..", "node_modules", pkg, "files"), // hoisted root
  ];
  for (const c of candidates) {
    if (existsSync(c)) return c;
  }
  const pkgJson = require.resolve(`${pkg}/package.json`);
  return join(dirname(pkgJson), "files");
}

/**
 * Locate the woff for one (id, subset, weight); fall back to a dir scan.
 * woff (NOT woff2) — react-pdf only supports TTF/WOFF, and its woff2 decoder
 * corrupts state across many fonts (see header note).
 */
function findWoff(dir, id, weight) {
  const exact = join(dir, `${id}-${SUBSET}-${weight}-normal.woff`);
  if (existsSync(exact)) return exact;
  const all = readdirSync(dir);
  const re = new RegExp(`^${id}-${SUBSET}.*-${weight}-normal\\.woff$`);
  const hit = all.find((f) => re.test(f)) ?? all.find((f) => f.includes(`-${SUBSET}-`) && f.endsWith(`-${weight}-normal.woff`));
  return hit ? join(dir, hit) : null;
}

const entries = [];
const warnings = [];
let totalBytes = 0;

for (const { family, pkg, weights } of FAMILIES) {
  let dir;
  try {
    dir = filesDir(pkg);
  } catch {
    warnings.push(`MISSING package ${pkg} — run pnpm install. Skipped ${family}.`);
    continue;
  }
  const fonts = [];
  for (const weight of weights) {
    const file = findWoff(dir, pkg.split("/")[1], weight);
    if (!file) {
      warnings.push(`No woff for ${family} ${weight} (${SUBSET}) in ${dir}`);
      continue;
    }
    const buf = readFileSync(file);
    totalBytes += buf.length;
    fonts.push({ src: `data:font/woff;base64,${buf.toString("base64")}`, fontWeight: weight });
  }
  if (fonts.length) entries.push({ family, fonts });
}

const body = entries
  .map(
    (e) =>
      `  {\n    family: ${JSON.stringify(e.family)},\n    fonts: [\n` +
      e.fonts
        .map((f) => `      { fontWeight: ${f.fontWeight}, src: ${JSON.stringify(f.src)} },`)
        .join("\n") +
      `\n    ],\n  },`
  )
  .join("\n");

const out = `// GENERATED by scripts/generate-fonts.mjs — DO NOT EDIT BY HAND.
// Run: pnpm --filter @carbon/documents generate:fonts
// Document fonts embedded as base64 woff data URIs (decoded in-process by
// react-pdf/fontkit; no network at render).

export type BundledFont = {
  family: string;
  fonts: { fontWeight: number; src: string }[];
};

export const BUNDLED_FONTS: BundledFont[] = [
${body}
];
`;

writeFileSync(OUT, out);

for (const w of warnings) console.warn(`⚠️  ${w}`);
console.log(
  `✓ Wrote ${OUT}\n  ${entries.length} families, ${entries.reduce((n, e) => n + e.fonts.length, 0)} faces, ${(totalBytes / 1024).toFixed(0)} KiB raw woff (~${((totalBytes * 1.34) / 1024).toFixed(0)} KiB base64).`
);
